# Generated by Django 3.1.1 on 2020-09-05 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesticide_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsubscription',
            name='on_issue_assign',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='emailsubscription',
            name='on_issue_status_change',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='emailsubscription',
            name='on_new_comment',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='emailsubscription',
            name='on_new_issue',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='emailsubscription',
            name='on_new_project',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='emailsubscription',
            name='on_project_membership',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='emailsubscription',
            name='on_project_status_change',
            field=models.BooleanField(default=True),
        ),
    ]
