# Generated by Django 3.1.1 on 2020-09-06 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesticide_app', '0002_auto_20200905_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(default='#775ada', max_length=10),
        ),
    ]
