# Generated by Django 3.1.1 on 2020-09-06 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesticide_app', '0003_auto_20200906_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuestatus',
            name='color',
            field=models.CharField(default='#217bf3', max_length=10),
        ),
        migrations.AlterField(
            model_name='issuestatus',
            name='type',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Closed', 'Closed'), ('Resolved', 'Resolved')], default='Pending', max_length=30),
        ),
    ]
